### ISSUE TITLE
关于搜索优化的建议

### ISSUE THREAD

**Issue by 1048562717** [magicblack/maccms_down#12]
希望搜索功能增加模糊搜索，比如影片名叫：如懿传，用户搜索如意转可以直接匹配到对应的影片，这样可以更好的留存用户，不会因为错别字而让用户认为没有对应片源而流失，希望老大可以增加此功能

**Comment by 1048562717** [comment]
因为大部分时候用户输入了错别字导致影片查找不到，用户自己也不会核对是否输入正确，这个如果能够优化的话就完美了！！

**Comment by magicblack** [comment]
感谢建议，这个比较麻烦且会增加额外性能开销，暂时不考虑哈。
