### ISSUE TITLE
is:open label:bug 苹果10更新后定时生成baidu.xml生成空白，去手台生成baidu.xml可以成功

### ISSUE THREAD

**Issue by lp8989** [magicblack/maccms_down#13]
is:open label:bug 苹果10更新后定时生成baidu.xml生成空白，去手台生成baidu.xml可以成功

**Comment by lp8989** [comment]
bug 苹果10更新后定时生成baidu.xml生成空白，去网站后台收动生成baidu.xml就显示.

**Comment by magicblack** [comment]
升级最新版试试。
