### ISSUE TITLE
1062版本定时任务出现curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by woaibooks** [magicblack/maccms_down#17]
1062版本定时任务出现curl: (52) Empty reply from server
是什么情况！

**Comment by magicblack** [comment]
1、特殊字符&被截断：
2、http协议问题：
有些朋友遇到的是协议不对，导致访问返回curl: (52) Empty reply from server，更改对应的协议即可
3、防火墙或者网络问题：
有时候服务器的防火墙会拦截一些请求，还有就是网络不通导致访问异常
