### ISSUE TITLE
新版本安装无法进入后台

### ISSUE THREAD

**Issue by xioahei20** [magicblack/maccms_down#20]
http://127.0.0.1/admin12.php/admin/index/index.html
一直出现这种页面,不知道是哪里出问题

**Comment by xioahei20** [comment]
![QQ图片20210306200201](https://user-images.githubusercontent.com/76814379/110206138-03a21180-7eb7-11eb-92fc-394370a54944.png)

**Comment by zj19920505** [comment]
喊你不要用ADMIN开头后台，主页要装个模板才行

**Comment by magicblack** [comment]
配置好nginx的 伪静态规则。 详情见包内
