### ISSUE TITLE
安装1022版采集后视频没有地址，播放器已安装，1020没问题

### ISSUE THREAD

**Issue by weilaiwy** [magicblack/maccms_down#3]
安装1022版采集后视频没有地址，播放器已安装，1020没问题。完整包，升级包都试过了
![1022](https://user-images.githubusercontent.com/59820554/72240258-88c8c800-361e-11ea-9994-3dc9cf3702ce.png)
![1020](https://user-images.githubusercontent.com/59820554/72240259-89f9f500-361e-11ea-9e91-5e32406cfd97.png)
![11222](https://user-images.githubusercontent.com/59820554/72240267-8cf4e580-361e-11ea-86c0-c88931e2b78f.png)
![212121](https://user-images.githubusercontent.com/59820554/72240271-8d8d7c00-361e-11ea-82e4-ca789b9aff57.png)

**Comment by magicblack** [comment]
整合插件失败。
