### ISSUE TITLE
删除某条视频的时候，能不能把本条视频附带的本地图片也一并清除

### ISSUE THREAD

**Issue by gudulv** [magicblack/maccms_down#30]
删除某条视频的时候，能不能把本条视频附带的本地图片也一并清除
![123](https://user-images.githubusercontent.com/63383664/129495659-65827f98-1115-499f-9b62-9b5b08f375b3.PNG)

**Comment by magicblack** [comment]
在视频管理中 删除一条视频会删除图片的。
