### ISSUE TITLE
数据库是5.6 后台查看重复数据的时候提示SQLSTATE[HY000]: 

### ISSUE THREAD

**Issue by aruoop** [magicblack/maccms_down#33]
数据库是5.6 后台查看重复数据的时候提示SQLSTATE[HY000]: General error: 1786 CREATE TABLE ... SELECT is forbidden when @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1.

是数据库版本问题还是啥
应该怎么处理呢

**Comment by magicblack** [comment]
参考这个：
https://github.com/magicblack/maccms10/issues/749

最新版已解决。
