### ISSUE TITLE
搜索页面报错，返回站点所有的视频数据

### ISSUE THREAD

**Issue by congruiIT** [magicblack/maccms_down#35]
测试PHP版本 72\73\74\80
maccms版本 2022.1000.3023
!2021_10_24 10_14_50.png](https://pic.baixiongz.com/uploads/2021/10/24/a023638cfbbf6.png)
搜索页面提示
search.html:1 Uncaught SyntaxError: Unexpected end of input

**Comment by magicblack** [comment]
请更新到最新版重试，如果还有问题到对应版本的github下提交。
