### ISSUE TITLE
加速推荐

### ISSUE THREAD

**Issue by anglesgirl** [magicblack/maccms_down#4]
https://cdn.jsdelivr.net/gh/magicblack/maccms_down/

你的gh仓库的东西，可以直接使用jsd进行全球加速 彻底解决raw域名过慢，被墙的问题

**Comment by anglesgirl** [comment]
关于这个加速的使用官方见官方网站
https://www.jsdelivr.com/

**Comment by magicblack** [comment]
感谢提议。
