### ISSUE TITLE
关于CMS的推送更新功能

### ISSUE THREAD

**Issue by 8dizhi** [magicblack/maccms_down#42]
当站长大佬有更新情况下
后台欢迎页面就会推送相关信息
具体路径 `/admin/index/welcome.html`
本人想做到完全离线操作，希望可去除检查更新的代码
`<script src="//update.maccms.la/v10/?c=check&v=Cms版本&p=PHP版本&tp=参数1&t=参数2"></script>` 
目前没找到相关检查代码，希望大佬告知位置！
之后我会下载离线包手动更新，
此属于本人这种强迫症用户使用的方案，望大佬理解。

**Comment by magicblack** [comment]
在 `static/js/admin_common.js` 第17行那部分，删除即可~
