### ISSUE TITLE
Hello . How to enter advertisement in cms 10 panel?

### ISSUE THREAD

**Issue by nexagensoftware** [magicblack/maccms_down#43]
此仓库提交issue将不被处理，请知悉。
Hello . How to enter advertisement in cms 10 panel?
v10版本：
https://github.com/magicblack/maccms10/issues

v8版本：
https://github.com/magicblack/maccms8/issues

**Comment by nexagensoftware** [comment]
Hello . How to enter advertisement in cms 10 panel?

**Comment by nexagensoftware** [comment]
Hello . How to enter advertisement in cms 10 panel?

**Comment by magicblack** [comment]
后台 - 模板 - 广告位管理 试试~
