### ISSUE TITLE
苹果cmsV8使用火车头入库，采集参数配置不受控制

### ISSUE THREAD

**Issue by xqd360** [magicblack/maccms_down#7]
苹果cmsV8使用火车头入库，苹果cmsV8程序内采集参数配置不受控制，不管是火车头新采集的数据还是更新原有的数据，火车头都是返回发布成功状态，导致再次采集更新时火车头下载的图片会重复上传，是否是因为采集参数配置不受控制导致？

**Comment by magicblack** [comment]
请到maccms8库里提问解决。
