### ISSUE TITLE
最新版1022C 采集资源出现bug

### ISSUE THREAD

**Issue by putiziya** [magicblack/maccms_down#8]
刚下载V8最新版1022C 采集资源出现bug , 不论在本地环境，还是服务器环境都出现这个问题

![QQ图片20200713030536](https://user-images.githubusercontent.com/68200710/87254552-067a6d00-c4b6-11ea-92be-3bbac19a91e5.png)

**Comment by magicblack** [comment]
php 用的什么版本。更新到最新试试。
